<!DOCTYPE html>
<html lang="zh-Hans">
<head>

  <meta charset="utf-8" />

  
  <title>Gevent 的 KeyError</title>

  
  





  
  <meta name="author" content="BWANGEL" />
  <meta name="description" content="摘要:
  本文翻译自 StackOverFlow 上的一篇答案 本文主要解释了gevent的猴子补丁和一个KeyError之间的关系   
" />

  
  
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@gohugoio" />
    <meta name="twitter:title" content="Gevent 的 KeyError" />
    <meta name="twitter:description" content="摘要:
  本文翻译自 StackOverFlow 上的一篇答案 本文主要解释了gevent的猴子补丁和一个KeyError之间的关系   
" />
    <meta name="twitter:image" content="/img/avatar.jpg" />
  

  
  <meta property="og:type" content="article" />
  <meta property="og:title" content="Gevent 的 KeyError" />
  <meta property="og:description" content="摘要:
  本文翻译自 StackOverFlow 上的一篇答案 本文主要解释了gevent的猴子补丁和一个KeyError之间的关系   
" />
  <meta property="og:url" content="/2016/09/14/gevent-%E7%9A%84-keyerror/" />
  <meta property="og:image" content="/img/avatar.jpg" />




<meta name="generator" content="Hugo 0.40.3" />


<link rel="canonical" href="/2016/09/14/gevent-%E7%9A%84-keyerror/" />

<meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="format-detection" content="telephone=no,email=no,adress=no" />
<meta http-equiv="Cache-Control" content="no-transform" />


<meta name="robots" content="index,follow" />
<meta name="referrer" content="origin-when-cross-origin" />







<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="Keep Foolish" />
<meta name="msapplication-tooltip" content="Keep Foolish" />
<meta name='msapplication-navbutton-color' content="#5fbf5e" />
<meta name="msapplication-TileColor" content="#5fbf5e" />
<meta name="msapplication-TileImage" content="/img/tile-image-windows.png" />
<link rel="icon" href="/img/favicon.ico" />
<link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png" />
<link rel="icon" sizes="192x192" href="/img/touch-icon-android.png" />
<link rel="apple-touch-icon" href="/img/touch-icon-apple.png" />
<link rel="mask-icon" href="/img/safari-pinned-tab.svg" color="#5fbf5e" />



<link rel="stylesheet" href="//cdn.bootcss.com/video.js/6.2.8/alt/video-js-cdn.min.css" />

<link rel="stylesheet" href="/css/bundle.bfaa7ffd11.css" />


  
  <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <script src="//cdn.bootcss.com/video.js/6.2.8/ie8/videojs-ie8.min.js"></script>
  <![endif]-->

<!--[if lte IE 11]>
    <script src="//cdn.bootcss.com/classlist/1.1.20170427/classList.min.js"></script>
  <![endif]-->


<script src="//cdn.bootcss.com/object-fit-images/3.2.3/ofi.min.js"></script>


<script src="//cdn.bootcss.com/smooth-scroll/12.1.4/js/smooth-scroll.polyfills.min.js"></script>


</head>
  <body>
    
    <div class="suspension">
      <a title="Go to top" class="to-top is-hide"><span class="icon icon-up"></span></a>
      
        
        <a title="Go to comments" class="to-comment" href="#gitment-container"><span class="icon icon-comment"></span></a>
        
      
    </div>
    
    
  <header class="site-header">
  <img class="avatar" src="/img/avatar.jpg" alt="Avatar">
  
  <h2 class="title">Keep Foolish</h2>
  
  <p class="subtitle">闻道百，以为莫己若者，我之谓也。</p>
  <button class="menu-toggle" type="button">
    <span class="icon icon-menu"></span>
  </button>
  <nav class="site-menu collapsed">
    <h2 class="offscreen">Main Menu</h2>
    <ul class="menu-list">
      
      
      
      
        <li class="menu-item
            
            
            
              is-active
            ">
            <a href="/">首页</a>
          </li>
      
        <li class="menu-item
            
            
            ">
            <a href="/tags">标签</a>
          </li>
      
        <li class="menu-item
            
            
            ">
            <a href="/about/">关于</a>
          </li>
      
    </ul>
  </nav>
  <nav class="social-menu collapsed">
    <h2 class="offscreen">Social Networks</h2>
    <ul class="social-list">

      
      <li class="social-item">
        <a href="mailto:bwangel.me@gmail.com" title="Email"><span class="icon icon-email"></span></a>
      </li>

      
      <li class="social-item">
        <a href="//github.com/bwangelme" title="GitHub"><span class="icon icon-github"></span></a>
      </li>

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      

      <li class="social-item">
        <a rel="alternate" type="application/rss+xml" href="/index.xml"><span class="icon icon-rss" title="RSS"></span></a>
      </li>

    </ul>
  </nav>
</header>

  <section class="main post-detail">
    <header class="post-header">
      <h1 class="post-title">Gevent 的 KeyError</h1>
      <p class="post-meta">@BWANGEL · 发表于 2016年9月14日 · 2 min read</p>
    </header>
    <article class="post-content"><p><strong>摘要</strong>:</p>

<blockquote>
<ol>
<li>本文翻译自 StackOverFlow 上的一篇<a href="http://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run">答案</a></li>
<li>本文主要解释了<code>gevent</code>的猴子补丁和一个<code>KeyError</code>之间的关系</li>
</ol>
</blockquote>

<p></p>

<h2 id="错误描述">错误描述</h2>

<p>在包含有<code>gevent.monkey.patch_thread()</code>( gevent 的猴子补丁)的程序中，运行时会报出下面的错误：</p>

<pre><code>Exception KeyError: KeyError(140468381321488,) in &lt;module 'threading' from '/usr/lib/python2.7/threading.pyc'&gt; ignored
</code></pre>

<p>解决答案: <a href="http://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run">KeyError in module &lsquo;threading&rsquo; after a successful py.test run</a></p>

<h2 id="原文翻译">原文翻译</h2>

<p>我观察了同样的主题，然后决定去精确地描述一下到底发生了什么。让我们一起来看一下我的发现，我希望这在以后能够帮助到其他人。</p>

<h3 id="简短的回答">简短的回答</h3>

<p>它的确和<code>threading</code>模块的猴子补丁有关。事实上，我能够轻易地开启这个异常，通过在猴子补丁线程之前导入<code>threading</code>模块。下面这两行代码就足够了：</p>
<div class="highlight"><pre class="chroma"><code class="language-python" data-lang="python"><span class="kn">import</span> <span class="nn">threading</span>
<span class="kn">import</span> <span class="nn">gevent.monkey</span><span class="p">;</span> <span class="n">gevent</span><span class="o">.</span><span class="n">monkey</span><span class="o">.</span><span class="n">patch_thread</span><span class="p">()</span></code></pre></div>
<p>上面的代码执行的时候，就报出了 &ldquo;忽略了一个<code>KeyError</code>&rdquo; 的信息：</p>
<div class="highlight"><pre class="chroma"><code class="language-sh" data-lang="sh"><span class="o">(</span>env<span class="o">)</span>czajnik@autosan: python test.py
Exception KeyError: KeyError<span class="o">(</span><span class="m">139924387112272</span>,<span class="o">)</span> in &lt;module <span class="s1">&#39;threading&#39;</span> from <span class="s1">&#39;/usr/lib/python2.7/threading.pyc&#39;</span>&gt; ignored</code></pre></div>
<p>如果你交换一下<code>import</code>行的顺序，这个错误信息就会消失了。</p>

<h3 id="详细的回答">详细的回答</h3>

<p>我可以在这里停止我的调试，但是我觉得它值得让我去了解，造成问题的准确的原因是什么？</p>

<p>第一步是去寻找打印这个忽略了异常的信息的代码。这对于我来说找到这个有点困难（在 python 标准库中 grep 查找<code>Exception .*ignored</code>没有返回任何东西），但是 grep CPython 的源码，我最终在<a href="http://svn.python.org/projects/python/tags/r27/Python/errors.c"> Python/error.c </a>文件中找到了一个函数叫做<code>void PyErr_WriteUnraisable(PyObject *obj)</code>，它的注释非常有趣，</p>
<div class="highlight"><pre class="chroma"><code class="language-c" data-lang="c"><span class="cm">/* Call when an exception has occurred but there is no way for Python
</span><span class="cm">   to handle it.  Examples: exception in __del__ or during GC. */</span></code></pre></div>
<p>我决定去检查谁调用了它，这个利用了<code>gdb</code>的一点功能来实现的，最终得到了如下的C调用栈，</p>

<pre><code>#0  0x0000000000542c40 in PyErr_WriteUnraisable ()
#1  0x00000000004af2d3 in Py_Finalize ()
#2  0x00000000004aa72e in Py_Main ()
#3  0x00007ffff68e576d in __libc_start_main (main=0x41b980 &lt;main&gt;, argc=2,
    ubp_av=0x7fffffffe5f8, init=&lt;optimized out&gt;, fini=&lt;optimized out&gt;,
    rtld_fini=&lt;optimized out&gt;, stack_end=0x7fffffffe5e8) at libc-start.c:226
#4  0x000000000041b9b1 in _start ()
</code></pre>

<p>现在我们可以清楚地看到异常是在<a href="https://docs.python.org/3/c-api/init.html#Py_Finalize">Py_Finalize</a>执行的时候抛出的，这个调用负责关闭Python解释器，释放已经申请的内存等等。它仅仅在退出前调用。</p>

<p>下一步是去查看<code>Py_Finalize()</code>的代码（它存放在<a href="http://svn.python.org/projects/python/tags/r27/Python/pythonrun.c"> Python/pythonrun.c </a>）。  它做的非常靠前的一个调用是<code>wait_for_thread_shutdown()</code>，这个函数非常值得去看一下，因为我们知道问题是关于线程的。</p>

<p>这个函数反过来调用了<code>threading</code>模块中的<code>_shutdown()</code>可调用对象，非常好，我们现在可以返回Python代码了。</p>

<p>查看<code>threading.py</code> ,我发现了如下有趣的部分：</p>
<div class="highlight"><pre class="chroma"><code class="language-python" data-lang="python"><span class="k">class</span> <span class="nc">_MainThread</span><span class="p">(</span><span class="n">Thread</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">_exitfunc</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_Thread__stop</span><span class="p">()</span>
        <span class="n">t</span> <span class="o">=</span> <span class="n">_pickSomeNonDaemonThrad</span><span class="p">()</span>
        <span class="k">if</span> <span class="n">t</span><span class="p">:</span>
            <span class="k">if</span> <span class="n">__debug__</span><span class="p">:</span>
                <span class="bp">self</span><span class="o">.</span><span class="n">_note</span><span class="p">(</span><span class="s2">&#34;</span><span class="si">%s</span><span class="s2">: waiting for other threads&#34;</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span>
        <span class="k">while</span> <span class="n">t</span><span class="p">:</span>
            <span class="n">t</span><span class="o">.</span><span class="n">join</span><span class="p">()</span>
            <span class="n">t</span> <span class="o">=</span> <span class="n">_pickSomeNonDaemonThread</span><span class="p">()</span>
        <span class="k">if</span> <span class="n">__debug__</span><span class="p">:</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">_note</span><span class="p">(</span><span class="s2">&#34;</span><span class="si">%s</span><span class="s2">: exiting&#34;</span><span class="p">,</span> <span class="bp">self</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_Thread__delete</span><span class="p">()</span>

<span class="c1"># Create the main thread object,</span>
<span class="c1"># and make it available for the interpreter</span>
<span class="c1"># (Py_Main) as threading._shutdown.</span>

<span class="n">_shutdown</span> <span class="o">=</span> <span class="n">_MainThread</span><span class="p">()</span><span class="o">.</span><span class="n">exitfunc</span></code></pre></div>
<p>很明显，<code>threading._shutdown()</code>函数调用的作用就是join所有的非服务化(non daemon)的线程，然后删除主线程（这意味着它确切做了什么）。我决定去给<code>threading.py</code>打一点补丁，用<code>try / except</code>包裹整个<code>_exitfunc()</code>函数体，用<code>traceback</code>模块来打印出系统调用栈。这个给出了如下的追踪情况：</p>

<pre><code>Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/threading.py&quot;, line 785, in _exitfunc
    self._Thread__delete()
  File &quot;/usr/lib/python2.7/threading.py&quot;, line 639, in __delete
    del _active[_get_ident()]
KeyError: 26805584
</code></pre>

<p>现在我们知道了异常抛出的精确位置了，在<code>Thread__delete()</code>方法内。</p>

<p>接下来的故事在阅读一会<code>threading.py</code>的代码后就变得很明显。<code>_active</code>字典将所有已创建的线程的线程ID(由<code>_get_indent()</code>函数返回)映射到对应的线程实例上。当<code>threading</code>模块载入的时候，<code>_MainThread</code>类的实例总是会被创建，而且会被添加到<code>_active</code>字典中。（甚至没有创建其他线程的时候主线程实例也会创建）。</p>

<p>问题是当一个<code>_get_ident()</code>方法被<code>gevent</code>的猴子补丁打过补丁，原来映射的方法<code>thread.get_ident()</code>被猴子补丁替换成了<code>green_thread.get_ident()</code>。明显两个函数调用返回的主线程ID并不相同。</p>

<p>现在，如果一个<code>threading</code>模块在猴子补丁之前被载入，调用<code>_get_ident()</code>会返回主线程实例创建的时候添加到<code>_active</code>中的ID。而打上猴子补丁以后就会返回另外一个值，在调用<code>_eixtfunc()</code>的时候，就会在<code>del _active[_get_ident()]</code>语句上抛出异常。</p>

<p>与上面的情况相反，如果猴子补丁在<code>threading</code>模块载入之前被打上了，所有的就都会正常。因为<code>_MainThread</code>实例被添加到<code>_active</code>中和<code>_get_ident()</code>都是在打补丁之后调用的，这样在清理线程的时候就会返回同样的线程ID。就是这样了。</p>

<p>为了确保以正确的顺序导入模块，我在我的电脑中添加了如下的代码片段，仅仅在打上猴子补丁之前调用：</p>
<div class="highlight"><pre class="chroma"><code class="language-python" data-lang="python"><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">if</span> <span class="s1">&#39;threading&#39;</span> <span class="ow">in</span> <span class="n">sys</span><span class="o">.</span><span class="n">modules</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">(</span><span class="s1">&#39;threading module loadded before patching!&#39;</span><span class="p">)</span>
<span class="kn">import</span> <span class="nn">gevent.monkey</span><span class="p">;</span> <span class="n">gevent</span><span class="o">.</span><span class="n">monkey</span><span class="o">.</span><span class="n">patch_thread</span><span class="p">()</span></code></pre></div>
<p>希望我的调试经历能够对你有用！</p></article>
    <footer class="post-footer">
      
      <ul class="post-tags">
        
          <li><a href="/tags/python"><span class="tag">Python</span></a></li>
        
          <li><a href="/tags/gevent"><span class="tag">Gevent</span></a></li>
        
          <li><a href="/tags/stackoverflow"><span class="tag">Stackoverflow</span></a></li>
        
          <li><a href="/tags/%E7%BF%BB%E8%AF%91"><span class="tag">翻译</span></a></li>
        
      </ul>
      
      <p class="post-copyright">
        本博客所有文章除特别声明外，均采用 <a href='http://creativecommons.org/licenses/by-nc-sa/3.0/cn/' rel='external nofollow' target='_blank'>CC BY-NC-SA 3.0 CN</a> 许可协议。转载请注明出处！
      </p>
    </footer>
    
      <div id="gitment-container"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
  (function() {
    var page_url = decodeURI("/2016/09/14/gevent-%E7%9A%84-keyerror/");
    var page_uniqueid = "d97b4e407ea5da96badd41c38a942fac";

    if (page_url.length >= 50) {
      console.log("文章的路径", "[" + page_url + "]:" + page_url.length, "超过了50个字符，使用 UniqueID 设置评论ID");
      comment_id = page_uniqueid
    } else {
      comment_id = page_url
    }

    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      console.log(comment_id, comment_id.length);
      document.getElementById('gitment-container').innerHTML = 'Gitment comments not available by default when the website is previewed locally.';
    } else {
      var gitment = new Gitment({
        id: comment_id,
        owner: "bwangelme",
        repo: "blog-comment",
        oauth: {
          client_id: "57954aa9925858cd8b32",
          client_secret: "1bfbecbae2fe6a1d288a56198b112cf44912cec7",
        },
      })
      gitment.render('gitment-container');
    }
  })();
</script>

      
    
  </section>
  <footer class="site-footer">
  <p>© 2017-2018 Keep Foolish</p>
  <p>Powered by <a href="https://gohugo.io/" target="_blank">Hugo</a> with theme <a href="https://github.com/laozhu/hugo-nuo" target="_blank">Nuo</a>.</p>
  
</footer>



<script async src="//cdn.bootcss.com/video.js/6.2.8/alt/video.novtt.min.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [['$','$'], ['\\(','\\)']],
      displayMath: [['$$','$$'], ['\\[','\\]']],
      processEscapes: true,
      processEnvironments: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
      TeX: { equationNumbers: { autoNumber: "AMS" },
      extensions: ["AMSmath.js", "AMSsymbols.js"] }
    }
  });
</script>
<script type="text/x-mathjax-config">
  // Fix <code> tags after MathJax finishes running. This is a
  // hack to overcome a shortcoming of Markdown. Discussion at
  // https://github.com/mojombo/jekyll/issues/199
  MathJax.Hub.Queue(() => {
    MathJax.Hub.getAllJax().map(v => v.SourceElement().parentNode.className += ' has-jax');
  });
</script>

<script src="/js/bundle.4830e45d80.js"></script>


<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-89788711-1', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>





  </body>
</html>
